cask_args appdir: "/Applications"

tap 'caskroom/cask'
tap 'homebrew/services'

brew 'ansible'
brew 'arping'
brew 'bash'
brew 'bash-completion'
brew 'bettercap'
brew 'bmon'
brew 'ccat'
brew 'coreutils'
brew 'cowsay'
brew 'ctags'
brew 'ctop'
brew 'curl', args: ['with-c-ares', 'with-gssapi', 'with-libmetalink', 'with-libssh2', 'with-nghttp2', 'with-rtmpdump', 'with-openssl']
brew 'dnsmasq'
brew 'fcrackzip'
brew 'fd'
brew 'ffmpeg', args: ['with-libass', 'with-aom', 'with-libssh', 'with-openh264', 'with-openjpeg', 'with-openssl', 'with-rtmpdump', 'with-webp']
brew 'fortune'
brew 'fzf'
brew 'geoip'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'grep'
brew 'hping'
brew 'htop'
brew 'hydra'
brew 'iftop'
brew 'imagemagick'
brew 'irssi'
brew 'john-jumbo'
brew 'jq'
brew 'jump'
brew 'lua'
brew 'lynis'
brew 'masscan'
brew 'mitmproxy'
brew 'neovim'
brew 'ngrep'
brew 'nmap'
brew 'node'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'rkhunter'
brew 'ripgrep'
brew 'ruby'
brew 'shellcheck'
brew 'socat'
brew 'speedtest-cli'
brew 'sqlite', args: ['universal', 'with-docs', 'with-fts']
brew 'sqlmap'
brew 'tarsnap'
brew 'tig'
brew 'tmux'
brew 'tor'
brew 'tree'
brew 'ttygif'
brew 'ttyrec'
brew 'unrar'
brew 'vim', args: ['with-lua', 'with-luajit', 'with-override-system-vi']
brew 'watch'
brew 'wget', args: ['with-iri']
brew 'xz'
brew 'you-get'
brew 'youtube-dl'

mas 'cointick', id: 1141688067

cask 'beardedspice'
cask 'brave-browser'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'oversight'
cask 'stremio'
cask 'slack'
cask 'spotify'
cask 'transmission'
cask 'vlc'
