tap 'homebrew/services'
tap 'homebrew/cask-fonts'
tap 'mvrilo/taps'

brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'bottom'
brew 'coreutils'
brew 'ctags'
brew 'ctop'
brew 'curl'
brew 'direnv'
brew 'dnsmasq'
brew 'duf'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'gnupg'
brew 'go'
brew 'htop'
brew 'jq'
brew 'lima'
brew 'luajit', args: ['HEAD']
brew 'neovim', args: ['HEAD']
brew 'nmap'
brew 'node'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'rkhunter'
brew 'rust-analyzer'
brew 'shellcheck'
brew 'speedtest-cli'
brew 'sqlite'
brew 'tmux'
brew 'tree'
brew 'tree-sitter', args: ['HEAD']
brew 'vim'
brew 'wget'
brew 'you-get'
brew 'youtube-dl'
brew 'hwatch'

mas 'whatsapp-desktop', id: 1147396723
mas 'tailscale', id: 1475387142

cask '1password'
cask 'alacritty'
cask 'brave-browser'
cask 'bluesnooze'
cask 'docker'
cask 'lulu'
cask 'oversight'
cask 'netiquette'
cask 'stremio'
cask 'slack'
cask 'rectangle'
cask 'spotify'
cask 'telegram'
cask 'transmission'
cask 'vlc'
